#include"HTMLWriter.h"
#include<fstream>
#include<iostream>
using namespace std;

HTMLWriter::HTMLWriter()
{
	cout << this <<" Child Class's default constructor called()" << "\n";
	//defautl 파일 이름
	this->fileName = "UN_TITLED.html";

	//default font지정
	this->fontName = "굴림";
	this->fontSize = 3;
	this->fontColor = "black";
}

//부모 class의 생성자 지정 하기
HTMLWriter::HTMLWriter(const string& fileName, const string& fileContent)
	:DocWriter(fileName, fileContent)
{
	cout << this << " Child Class's 2 arguments constructor called()" << "\n";
	//default 폰트를 지정한다.
	this->fontName = "굴림";
	this->fontSize = 3;
	this->fontColor = "black";
}

HTMLWriter::~HTMLWriter()
{
	cout << this <<" Child Class's destructor called()" << "\n";
}

void HTMLWriter::setFont(const string& fontName, const int& fontSize, const string& fontColor)
{
	this->fontName = fontName;
	this->fontSize = fontSize;
	this->fontColor = fontColor;
}

//html파일 생성 
void HTMLWriter::write()
{
	//파일을 연다.
	ofstream of(this->fileName.c_str());

	//HTML헤더 부분 저장.
	of << "<HTML><HEAD><TITLE>THIS DOCUMENTS IS GENERATED BY HTMLWRITER</TITLE></HEAD><BODY>";
	of << "<H1>Content</H1>";

	//font 태그 시작
	of << "<Font name ='" << this->fontName << "' size = '" << this->fontSize << "' color = '" << this->fontColor << "'>";

	//text를 저장한다.
	of << this->content;

	//font 태그 닫음
	of << "</FONT>";

	//HTML 마무리
	of << "</BODY></HTML>";
}