#include"HTMLWriter.h"
#include<fstream>
using namespace std;

HTMLWriter::HTMLWriter()
{
	this->fileName = "UN_TITLED.html";
	this->fontName = "굴림";
	this->fontSize = 3;
	this->fontColor = "black";
}

HTMLWriter::HTMLWriter(const string& fileName, const string& fileContent)
	:DocWriter(fileName, fileContent)
{
	this->fontName = "굴림";
	this->fontSize = 3;
	this->fontColor = "black";
}

HTMLWriter::~HTMLWriter()
{

}

void HTMLWriter::setFont(const string& fontName, const int& fontSize, const string& fontColor)
{
	this->fontName = fontName;
	this->fontSize = fontSize;
	this->fontColor = fontColor;
}

void HTMLWriter::write()
{
	//파일을 연다.
	ofstream of(this->fileName.c_str());

	//HTML헤더 부분 저장.
	of << "<HTML><HEAD><TITLE>THIS DOCUMENTS IS GENERATED BY HTMLWRITER</TITLE></HEAD><BODY>";
	of << "<H1>Content</H1>";

	//font 태그 시작
	of << "<Font name ='" << this->fontName << "' size = '" << this->fontSize << "' color = '" << this->fontColor << "'>";

	//text를 저장한다.
	of << this->content;

	//font 태그 닫음
	of << "</FONT>";

	//HTML 마무리
	of << "</BODY></HTML>";
}